### ISSUE TITLE
Removing Premade Elements

### ISSUE THREAD

**Issue by NotCoolKiwi** [l2wilson94/SandPond#3]
I would like to remove all of the premade elements so that I can custom-make all the elements so I can learn the language from the ground up. But, every time I remove the element files in Source/Elements, the menu no longer works. I think this is a great language and it could be very helpful! Thank you so much to anyone that can help me!

**Comment by l2wilson94** [comment]
That's a good idea! I'll be able to have a look at fixing that today or tomorrow.

**Comment by NotCoolKiwi** [comment]
Thank you so much!

**Comment by l2wilson94** [comment]
Hi! I think I fixed it on the main branch. Please let me know if it still doesn't work :)

**Comment by NotCoolKiwi** [comment]
Thank you! I will try it again when I am done with work and post here if it works!

**Comment by NotCoolKiwi** [comment]
Yay! It works! Thank you for fixing this!

**Comment by NotCoolKiwi** [comment]
Actually, am I doing something wrong or is this another bug related to this?

The element does not show up in the menu once I add a rule to it.

My code looks like this (in the customelements.js file)


SpaceTode `

element Sand {

    colour "yellow"

    rule {
        @ => _
        _    @
    }

}

`

**Comment by NotCoolKiwi** [comment]
it works fine without the rule though

**Comment by l2wilson94** [comment]
Have you tried opening the console in the web browser? It might give you an error message. I'm wondering, maybe it could be because those `@` and `_` symbols aren't defined (if you removed all the other element files). I would recommend keeping the `Globals.js` file - it doesn't make any elements - it just defines some symbols to get you started. Here it is: https://github.com/l2wilson94/SandPond/blob/main/Source/Elements/Globals.js

**Comment by NotCoolKiwi** [comment]
Yes, Thank You! Adding the Globals file made it work.

**Comment by l2wilson94** [comment]
Great! Please feel free to let me know if you want any more help with anything :)

**Comment by NotCoolKiwi** [comment]
Okay, thank you!
